export * from './patientModel';
export * from './resolutionModel';
export * from './userModel';
export * from './appointmentsModel';
export * from './adminsModel';
export * from './doctorsModel';
export * from './doctorSpecializationsModel';
export * from './specializationsModel';
export * from './appointmentsStatusesModel';
